#! /usr/bin/env python
def build(bld):
    # ex_ea
    bld.program(features = 'cxx',
                   source = 'ex_ea.cpp',
                   includes = '../',
                   uselib = 'TBB BOOST EIGEN PTHREAD MPI',
                   use = 'sferes2',
                   target = 'ex_ea')

    # ex_ea
    bld.program(features = 'cxx',
                   source = 'ex_ea_mpi.cpp',
                   includes = '../',
                   uselib = 'TBB BOOST EIGEN PTHREAD MPI',
                   use = 'sferes2',
                   target = 'ex_ea_mpi')

    # ex_nsga2
    bld.program(features = 'cxx',
                   source = 'ex_nsga2.cpp',
                   includes = '../',
                   uselib = 'TBB BOOST EIGEN PTHREAD MPI',
                   use = 'sferes2',
                   target = 'ex_nsga2')

    # ex_eps_moea
    bld.program(features = 'cxx',
                   source = 'ex_eps_moea.cpp',
                   includes = '../',
                   uselib = 'TBB BOOST EIGEN PTHREAD MPI',
                   use = 'sferes2',
                   target = 'ex_eps_moea')


    # ex_map_elites
    bld.program(features = 'cxx',
                   source = 'ex_map_elites.cpp',
                   includes = '../',
                   uselib = 'TBB BOOST EIGEN PTHREAD KDTREE',
                   use = 'sferes2',
                   target = 'ex_map_elites')
