
#! /usr/bin/env python

from waflib.Configure import conf

def options(opt):
    pass

def build(bld):
    bld.program(features = 'cxx',
                   source = 'example.cpp',
                   includes = '. ../../',
                   uselib = 'EIGEN BOOST BOOST_UNIT_TEST_FRAMEWORK TBB ',
                   use = 'sferes2',
                   target = 'example')
